// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nytwyuimnmjliivgdorg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55dHd5dWltbm1qbGlpdmdkb3JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDk2MTksImV4cCI6MjA2OTgyNTYxOX0.92qvKxRVe43f85zh5hkmxHgixKwugsJFWNQJX2vBEmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});